language: python
branches:
    only:
        - master
python:
    - "2.7"
    - "3.3"
    - "3.5"
    - "3.6"
install:
    - pip install -r requirements-dev.txt
    - pip install coveralls
script:
    - py.test --cov=pyopenapi --cov-config=.coveragerc pyopenapi/tests
after_success:
    - coveralls

